### ISSUE TITLE
Sdist on PyPI

### ISSUE THREAD

**Issue by dairiki** [ko-zu/psl#1]
Thank you for writing `publicsuffixlist`!

For those of us using buildout or other non-wheel-aware installers (or at least for me) it would be convenient to have an *sdist* available on PyPI.  Could I bother you to upload one?

**Comment by ko-zu** [comment]
Added both .tar.gz and wheel from v0.2.11 https://github.com/ko-zu/psl/commit/dcca2191d028134b17da182452062970b338783c https://pypi.python.org/pypi/publicsuffixlist

Thanks

**Comment by dairiki** [comment]
Thanks!
