### ISSUE TITLE
Public Suffix data incorrect?

### ISSUE THREAD

**Issue by MarkBaggett** [ko-zu/psl#14]
Hello,
Thank you for this project.  If I am understanding the purpose of these methods correctly then I believe the parser is pulling the incorrect information.  Its my understanding that the eTLD (effective top level domain) where an organization could register a private domain would be places like ".com" and "com.uk" would be "public suffixes".  The domain that someone would register there such as "google.com" and "google.com.uk" would both be "private suffixes".   However, that isn't what the tool produces.
```
>>> PublicSuffixList().is_private("com.uk")   <-Should be False
True
>>> PublicSuffixList().is_private("com")
False
```
Furthermore if I try to retrieve the public and private suffixes I get incorrect data as well.
```
>>> PublicSuffixList().publicsuffix("google.com.uk")   <- should be com.uk
'uk'          
>>> PublicSuffixList().privatesuffix("google.com.uk")  <- Should be google.com.uk
'com.uk'
>>> PublicSuffixList().privatesuffix("google.com")     <- should be google.com and is correct
'google.com'
```

**Comment by ko-zu** [comment]
There is no declaration of `com.uk` in current builtin public suffix list. This project contains just a copy of upstream PSL. If you think `com.uk` should be declared in the PSL, you need to feed your own list locally, or contribute to the PSL project as described in https://github.com/publicsuffix/list/wiki/Guidelines

**Comment by MarkBaggett** [comment]
You are correct.  Sorry about that.   Thank you
