### ISSUE TITLE
Fails on ccTLDs

### ISSUE THREAD

**Issue by tzeppy** [ko-zu/psl#2]
Calling privatesuffix("something.com.mx") returns "com.mx".

**Comment by ko-zu** [comment]
Please check your psl source file. by default, PublicSuffixList assumes all unknown TLDs are publicsuffix.
```
In [2]: PublicSuffixList("").privatesuffix("example.com.mx")
Out[2]: 'com.mx'

In [3]: PublicSuffixList().privatesuffix("example.com.mx")
Out[3]: 'example.com.mx'
```
